import tensorflow as tf
hello = tf.constant("Hello")
world = tf.constant("World")
a = tf.constant(10)
b = tf.constant(20)
c = tf.ones((5,5)) 
fill_mat = tf.fill((10,10),10)
myrandn = tf.random_normal((5,5),mean=0,stddev=1.0)
myrandu = tf.random_uniform((5,5),minval=0,maxval=21)
with tf.Session() as sess:
    print(sess.run(hello+world +'\n'))
    print(sess.run(a+b))
    print(sess.run(fill_mat))
    print("\n")
    print(sess.run(c))
    print("\n")
    print(sess.run(myrandn))
    print("\n")
    print(sess.run(myrandu))
sess1 = tf.Session()
print(sess1.run(myrandu))
result = tf.matmul(myrandn,myrandu)
print(result.eval(session=sess1)) 